version: "3"
services:
  frontend:
    image: changkiyun/final-project-frontend
    build:
      context: .
      args:
        - REACT_APP_API_REQUEST_URL=${REACT_APP_API_REQUEST_URL}
        - REACT_APP_WEBSOCKET_SUB_URL=${REACT_APP_WEBSOCKET_SUB_URL}
        - REACT_APP_WEBSOCKET_PUB_URL=${REACT_APP_WEBSOCKET_PUB_URL}  # 빌드타임에 환경변수를 리엑트로 전달
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true
    mem_limit: 128m
    environment:
      REACT_APP_API_REQUEST_URL: ${REACT_APP_API_REQUEST_URL}
      REACT_APP_WEBSOCKET_SUB_URL: ${REACT_APP_WEBSOCKET_SUB_URL}
      REACT_APP_WEBSOCKET_PUB_URL: ${REACT_APP_WEBSOCKET_PUB_URL}

  nginx: 
    restart: always
    image: changkiyun/final-project-nginx
    ports: 
      - "80:80"

  backend:
    image: changkiyun/final-project-backend
    ports:
      - "8080:8080"
    environment: 
      MYSQL_HOST: $MYSQL_HOST 
      MYSQL_USER: $MYSQL_USER 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_PORT: $MYSQL_PORT   

  # mysql:
  #   build: ./mysql
  #   restart: unless-stopped
  #   container_name: app_mysql
  #   ports:
  #     - "3306:3306"
  #   volumes:
  #     - ./mysql/mysql_data:/var/lib/mysql
  #     - ./mysql/sqls/:/docker-entrypoint-initdb.d/
  #   environment:
  #     MYSQL_ROOT_PASSWORD: johnahn
  #     MYSQL_DATABASE: myapp
