version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: ./FrontEnd/goorm
    volumes:
      - /app/node_modules
      - ./FrontEnd/goorm:/app
    stdin_open: true

  nginx: 
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "80:80"

  backend:
    build:
      dockerfile: Dockerfile
      context: ./BackEnd/goorm
    ports:
      - "8080:8080"
    # volumes:
    #   - ./:/app/

  database:
    build: ./mysql
    restart: unless-stopped
    container_name: maria-test
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/mysql_data:/var/lib/mysql
      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp