#local setting
spring:
  profiles:
    activate:
      on-profile: local
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/balgoorm-test
    username: balgoorm
    password:

  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update
