# prod setting
spring:
  profiles:
    activate:
      on-profile: rds
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://final-project-database.cryge2oy0mud.ap-northeast-2.rds.amazonaws.com:3306/goorm
    username: root
    password: dbsckdrl12
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        security: DEBUG

