# prod setting
spring:
  profiles:
    activate:
      on-profile: prod
  datasource:
    driverClassName: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}
    username: ${MYSQL_USER}
    password: ${MYSQL_ROOT_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        show_sql: true
        format_sql: true
    hibernate:
      ddl-auto: update

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 6eb005afd4685fa7dd9733beac01c3db #${KAKAO_CLIENT_ID}
            client-secret: 4o3UFEdtirm1XlmxouaWpFVixFeiEtAc #${KAKAO_CLIENT_SECRET}
            redirect-uri: http://final-project-app-env.eba-xdjqmujd.ap-northeast-2.elasticbeanstalk.com/login/oauth2/code/kakao
            client-authentication-method: client_secret_post
            authorization-grant-type: authorization_code
            scope: # kakao 개인 정보 동의 항목 설정의 ID 값
              - profile_nickname
              - profile_image
              - account_email
            client-name: kakao

        # kakao provider 설정
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id # 유저 정보 조회 시 반환되는 최상위 필드명으로 해야 한다.

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        security: DEBUG

login:
  register-url: http://127.0.0.1:5500/register.html
  loginSuccess-url : http://127.0.0.1:5500/main.html

board:
  page:
    size: 10

cloud:
  aws:
    credentials:
      accessKey: ${AWS_CREDENTIALS_ACCESS_KEY}
      secretKey: ${AWS_CREDENTIALS_SECRET_KEY}
    s3:
      bucketName: bangbumdae-images
    region:
      static: ap-northeast-2
    stack:
      auto: false

data:
  apiKey: MN6yZ24amfOMX7NPDMv25PBIUdw4zXtBml18P15%2Fu1wvmWbdrTAcjn4tE67yh7kybg5kLNDoPSBLr9mjn8SFxQ%3D%3D